### ISSUE TITLE
Enable Light Adjustment setting doesn't keep its settings upon restart

### ISSUE THREAD

**Issue by RisPNG** [Provismet/Dynamic-Fullbright#2]
### Type of Error

Incorrect Behaviour

### Description

The "Enable Light Adjustment" will always set to "No" upon startup. I am running Quilt 0.19.1 on Minecraft 1.20.1. It's a bit of a hassle to enable it everytime I boot up Minecraft.

### Mod Version

dynamic-fullbright-1.0.1.jar

### Minecraft Version

1.20.1

### Mod Loader

Quilt

### Steps to Reproduce

```bash
1. Launch Minecraft
2. Go to Mods -> Dynamic Fullbright settings
3. Set "Enable Light Adjustment" to "Yes"
4. Re-launch Minecraft
5. "Enable Light Adjustment" will be reset to "No"
```

**Comment by Provismet** [comment]
I tried recreating the issue as described, but everything is working as intended for me. I'll need some more information to so I can solve the problem:  
Are _all_ of the settings failing to save, or is it only the _Enable Lighting Adjustment_ option?

**Comment by RisPNG** [comment]
> I tried recreating the issue as described, but everything is working as intended for me. I'll need some more information to so I can solve the problem: Are _all_ of the settings failing to save, or is it only the _Enable Lighting Adjustment_ option?

My bad, upon further testing it seems like my initial report was correct. Only the `Enable Lighting Adjustment` option is affected. Everything else saved fine.

I dug a little bit further and found the config file and I think I understand why the option isn't saved.
_dynamic-fullbright.json_
```
{
	"separate entity lighting": false,
	"scaling": true,
	"min block": 3,
	"max block": 15,
	"min entity": 3,
	"max entity": 15,
	"min sky": 3,
	"max sky": 15
}
```

It seems like the option for the `Enable Lighting Adjustment` isn't there. Even though I have set it to "Yes" in the in-game mods settings.

**Comment by Provismet** [comment]
So this is actually working as intended, the button for "Enable Light Adjustment" was only ever there to turn the mod on/off for anyone who hasn't set a keybind to do so in the controls menu.

If this is an issue, I could add a new setting for "keep mod on" or something so if one prefers, the mod will remember its on/off state when Minecraft is opened.

**Comment by RisPNG** [comment]
> So this is actually working as intended, the button for "Enable Light Adjustment" was only ever there to turn the mod on/off for anyone who hasn't set a keybind to do so in the controls menu.
> 
> If this is an issue, I could add a new setting for "keep mod on" or something so if one prefers, the mod will remember its on/off state when Minecraft is opened.

I would love that to be an option, thank you for your consideration.
