### ISSUE TITLE
High min skylight looks wrong

### ISSUE THREAD

**Issue by Moonyol** [Provismet/Dynamic-Fullbright#5]
### Type of Error

Incorrect Behaviour

### Description

Min skylight 15
![2024-01-17_21 51 00](https://github.com/Provismet/Dynamic-Fullbright/assets/92951072/054e9c09-f984-4568-afd4-389ffb040b83)
Min skylight 0
![2024-01-17_21 50 56](https://github.com/Provismet/Dynamic-Fullbright/assets/92951072/83188fae-3ab4-481d-8931-def6075de92a)

I was expecting it to make the surface bright but the underground dark
sodium fixes some of the blocks being bright but the entities still are

Fabric 0.15.3-1.20.4
(NVIDIA GTX 1660)

### Mod Version

1.2.0

### Minecraft Version

1.20 (Latest)

### Mod Loader

Fabric

### Steps to Reproduce

```
0. get mod menu and cloth config
1. enable light adjustment and set minimum sky light level to 15
2. look at the world
```

**Comment by Provismet** [comment]
Is this issue only present with Sodium? Or does it happen regardless of Sodium's inclusion?

**Comment by Moonyol** [comment]
it happens without sodium too, sodium just fixes the grass and flowers being bright but entities are still bright with sodium
I typed it wrong in the issue before so I changed it

**Comment by Provismet** [comment]
I'll look into how to resolve this, until then the block light scaling should work.

**Comment by Provismet** [comment]
In a weird way, this is technically working as expected. Entity light being affected is just an oversight on my part.

In Minecraft "skylight" refers to how exposed you are to the sky. Skylight is 15 even at night. Try maxing the skylight during the day while underground.

![2024-01-20_22 12 28](https://github.com/Provismet/Dynamic-Fullbright/assets/17149901/9cdf97ae-5c56-4fb4-8fd3-b86117197195)
![2024-01-20_22 12 16](https://github.com/Provismet/Dynamic-Fullbright/assets/17149901/2cba6f45-cdbd-40d3-8cdb-59f2fb317817)

I'll work on adding controls for sky brightness, which was the original intention.
