### ISSUE TITLE
dont work

### ISSUE THREAD

**Issue by J4KU888** [Provismet/Dynamic-Fullbright#6]
### Type of Error

other

### Description

i load this mod to my minecraft instalation and it doesnt work

### Mod Version

1.0.1

### Minecraft Version

1.19

### Mod Loader

Fabric

### Steps to Reproduce

```bash

```

### Crash Log

```bash

```

**Comment by Provismet** [comment]
I'm going to need significantly more information than that. But you should also be aware that 1.19 versions are not a priority anymore.
